on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_assetlists:
    name: Validate edited wallet.json
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
          
      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate Wallet.json schema
        run: |
          for file in $(find . -name 'wallet.json'); do
            if ! jsonschema -i "$file" ./wallet.schema.json; then
              exit 1
            fi
          done
